name: Build and Deploy .NET Site

on:
  push:
    branches:
      - Project

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore LilyLandBlazorSite/LilyLandBlazorSite.sln

      - name: Build Project
        run: dotnet build LilyLandBlazorSite/LilyLandBlazorSite.sln --configuration Release --no-restore

      - name: Publish Project
        run: dotnet publish LilyLandBlazorSite/LilyLandBlazorSite.sln -c Release -o publish

      - name: Organize Files for Deployment
        run: |
          mkdir -p temp_publish
          mv publish/* temp_publish/ # Move everything out of publish
          mv temp_publish/wwwroot/* temp_publish/ # Move contents of wwwroot to root
          rm -rf temp_publish/wwwroot # Remove now-empty wwwroot directory
          mv temp_publish/* .
          rm -rf temp_publish

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Deploy everything in root
          publish_branch: Pages
